name: Build and Test Python
on:
  pull_request:
    paths:
      - payjoin-ffi/**
env:
  # Override the value from the rust-toolchain file
  # This is necessary because even though the correct toolchain
  # is explicitly specified for the rust-toolchain action,
  # rustup honors the rust-toolchain file over the default
  RUSTUP_TOOLCHAIN: 1.85

jobs:
  build-wheels-and-test:
    name: "Build and test Linux"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: payjoin-ffi/python
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
        python: ["3.12"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install Rust 1.85.0"
        uses: dtolnay/rust-toolchain@1.85.0

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: "Install build dependencies"
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-dev

      - uses: Swatinem/rust-cache@v2

      - name: "Generate linux payjoin-ffi.py and binaries"
        if: matrix.os == 'ubuntu-latest'
        run: |
            PYBIN=$(dirname $(which python))
            PYBIN="$PYBIN" bash ./scripts/bindgen_generate.sh

      - name: "Generate macos payjoin-ffi.py and binaries"
        if: matrix.os == 'macos-15'
        run: bash ./scripts/bindgen_generate.sh

      - name: "Build wheel"
        run: python -m build --wheel

      - name: "Install wheel"
        run: pip install ./dist/*.whl

      - name: "Run tests"
        run: |
          if [ "${{ matrix.os }}" = "macos-15" ]; then
            python -m unittest test/test_payjoin_unit_test.py -v
          else
            python -m unittest -v
          fi

