name: Build and Test Python
on:
  pull_request:
    paths:
      - payjoin-ffi/**

jobs:
  build-wheels-and-test:
    name: "Build and test Linux"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: payjoin-ffi/python
    strategy:
      matrix:
        include:
          - python: "3.9"
          - python: "3.10"
          - python: "3.11"
          - python: "3.12"
          - python: "3.13"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install Rust 1.85.0"
        uses: dtolnay/rust-toolchain@1.85.0

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: "Install build dependencies"
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-dev

      - name: "Use cache"
        uses: Swatinem/rust-cache@v2

      - name: "Generate payjoin-ffi.py and binaries"
        run: |
            PYBIN=$(dirname $(which python))
            PYBIN="$PYBIN" bash ./scripts/bindgen_generate.sh

      - name: "Build wheel"
        run: python -m build --wheel

      - name: "Install wheel"
        run: pip install ./dist/*.whl

      - name: "Run tests"
        run: python -m unittest -v

  build-macos-aarch64:
    name: "Build macOS aarch64"
    runs-on: macos-15
    defaults:
      run:
        working-directory: payjoin-ffi/python
    strategy:
      matrix:
        python: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.85.0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - uses: Swatinem/rust-cache@v2

      - name: Build aarch64 binary
        run: |
          rustup override set 1.85.0-aarch64-apple-darwin
          bash ./scripts/bindgen_generate.sh

      - name: Upload aarch64 binary
        uses: actions/upload-artifact@v4
        with:
          name: libpayjoin_ffi-aarch64
          path: ${{ github.workspace }}/payjoin-ffi/target/aarch64-apple-darwin/release-smaller/libpayjoin_ffi.dylib
  
  build-macos-x86_64:
    name: "Build macOS x86_64"
    runs-on: macos-13
    defaults:
      run:
        working-directory: payjoin-ffi/python
    strategy:
      matrix:
        python: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.85.0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - uses: Swatinem/rust-cache@v2
      
      - name: Build aarch64 binary
        run: |
          rustup override set 1.85.0-x86_64-apple-darwin
          bash ./scripts/bindgen_generate.sh

      - name: Log all Rust host binaries 1.85.0
        if: always()
        run: file $HOME/.rustup/toolchains/1.85.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/*

      - name: Log all Rust host binaries nightly
        if: always()
        run: file $HOME/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/*

      - name: Upload x86_64 binary
        uses: actions/upload-artifact@v4
        with:
          name: libpayjoin_ffi-x86_64
          path: ${{ github.workspace }}/payjoin-ffi/target/x86_64-apple-darwin/release-smaller/libpayjoin_ffi.dylib

  
  build-macos-merge:
    name: "Merge and test macOS universal binary"
    runs-on: macos-15
    needs: [build-macos-aarch64, build-macos-x86_64]
    defaults:
      run:
        working-directory: payjoin-ffi/python
    strategy:
      matrix:
        python: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      
      - name: Download aarch64 binary
        uses: actions/download-artifact@v4
        with:
          name: libpayjoin_ffi-aarch64
          path: ${{ github.workspace}}/payjoin-ffi/target/aarch64-apple-darwin/release-smaller
      
      - name: Download x86_64 binary
        uses: actions/download-artifact@v4
        with:
          name: libpayjoin_ffi-x86_64
          path: ${{ github.workspace }}/payjoin-ffi/target/x86_64-apple-darwin/release-smaller

      - name: Merge binaries
        run: bash ./scripts/generate_universal_macos.sh

      - name: Build wheel
        run: python -m build --wheel

      - name: Install wheel
        run: pip3 install ./dist/*.whl

      - name: Run tests
        run: python -m unittest -v
